- scripts/sql/DDL.sql
- scripts/sql/DML.sql
- src/main/java/com/service/core/config/async/AsyncConfig.java
- src/main/java/com/service/core/config/async/AsyncGenerator.java
- src/main/java/com/service/core/config/redis/RedisConfig.java
- src/main/java/com/service/core/mbti/domain/MbtiMetadata.java
- src/main/java/com/service/core/mbti/infrastructure/MbtiMetadataRepository.java
> release v0.0.1

- build.gradle
- scripts/sql/DDL.sql
- scripts/sql/DML.sql
- src/main/java/com/service/core/config/async/AsyncConfig.java
- src/main/java/com/service/core/config/async/AsyncGenerator.java
- src/main/java/com/service/core/config/redis/RedisConfig.java
- src/main/java/com/service/core/config/swagger/SwaggerConfig.java
- src/main/java/com/service/core/mbti/domain/MbtiMetadata.java
- src/main/java/com/service/core/mbti/infrastructure/MbtiMetadataRepository.java
- 프로젝트 실행시 에러 발생으로 인한 해결
- resolved #26 
- mac pro m1 error 문제로 인해 의존성 추가
- swagger3 과 spring 버전 호환문제로 인한 어노테이션 수정
- https://medium.com/@boysbee/unable-to-load-io-netty-resolver-dns-macos-macosdnsserveraddressstreamprovider-46d89bf74d42 
- https://shanepark.tistory.com/366
- 해결로 인한 변경사항이 다른 문제가 없는지, 혹은 더 나은 해결방안이 있는지
- 현재 main에 적용된 사항을 pull 받은 이후 커밋 후 PR을 통해 @DongGeon0908 님의 코드가 포함되어 있는데 해당 사항을 staging 브랜츠에 넣어도 되는지
-
> [Bug/run-time] 런타임 에러 해결 (#26)

- build.gradle
- scripts/sql/DDL.sql
- scripts/sql/DML.sql
- src/main/java/com/service/core/config/async/AsyncConfig.java
- src/main/java/com/service/core/config/async/AsyncGenerator.java
- src/main/java/com/service/core/config/redis/RedisConfig.java
- src/main/java/com/service/core/config/swagger/SwaggerConfig.java
- src/main/java/com/service/core/mbti/domain/MbtiMetadata.java
- src/main/java/com/service/core/mbti/infrastructure/MbtiMetadataRepository.java
- 어노테이션을 통한 문제해결보다 경로 일치 방식 변경을 통한 문제 해결이 문제가 적을 것이라 생각
- resolved #28
- EnableWebMvc 어노테이션 삭제, EnableSwagger2 어노테이션 다시 추가
- application.yml 파일 설정에서 spring.mvc.pathmatch.matching-strategy: ant_path_matcher 추가를 통해 경로 일치 방식을 변경
> [Fix/run time] Swagger 호환 문제 해결방안 변경

- build.gradle
- src/main/java/com/service/core/config/swagger/SpringfoxHandlerConfig.java
- swagger 3.0과 spring actuator 의존성 추가시 충돌
- resolved #43 
- 해당 문제의 경우 모두 endpoint 를 처리하는 과정에서 문제가 생기는 것 같음
- 검색을 통한 springfox 매핑핸들러 코드 추가하여 문제 해결 
- 해당 코드가 좋지 않은 내용이 있는지
-
> [Fix/actuator] Swagger3.0, Spring actuator 호환성 문제 해결

- build.gradle
- src/main/java/com/service/core/common/resttemplate/RestTemplateService.java
- src/main/java/com/service/core/config/swagger/SpringfoxHandlerConfig.java
- src/main/java/com/service/core/member/application/MemberService.java
- src/main/java/com/service/core/slack/presentation/SlackSchedulerService.java
- spring actuator 을 이용한 서버 상태를 spring scheduler를 이용하여 Slack에 메시지 보내기
- resolved #40 
- spring actuator를 통한 서버 상태 모니터링
- Rest Template를 통해 server health 받아오고 Slack으로 메시지 전달
- 해당 코드에 미흡한 부분 혹은 잘못된 부분
- 이후 기능 구현에 문제가 없고 시간이 된다면 resttemplate -> webclient로 변경
-
> [Feature/actuator] Spring actuator 서버 상태 Slack 전달 스케줄링 기능 구현

- src/main/java/com/service/core/common/resttemplate/RestTemplateService.java
- src/main/java/com/service/core/error/GlobalExceptionHandler.java
- src/main/java/com/service/core/slack/application/SlackSchedulerService.java
- 불필요 rest template 코드 제거
- resolved #55 
- Error log 시 slack appender 사용으로 불필요 rest template 코드 제거
- 특이사항 없음
-
> [Move/RestTemplate-2] 중복 로직 rest template 코드 제거

- .github/workflows/action.yml
- github action 을 통한 CI/CD 자동화 진행
- github action 기본폼 생성
- 잘못된 코드 구현이나 미흡한 부분 지적 요청
-
> [Docs/github-action-1] github action yml 기본 폼 생성

- build.gradle
- ec2 build 실패
- 해당 의존성 주입 추가
- 
-
> * :bug: ec2 의존성 주입 실패로 인한 slf4j 의존성 추가

- build.gradle
- 해당 문제가 아니므로 복구
- 해당 문제가 아니므로 복구
> Revert "* :bug: ec2 의존성 주입 실패로 인한 slf4j 의존성 추가"

- src/main/java/com/service/core/error/dto/ErrorMessage.java
- src/main/java/com/service/core/error/exception/letter/InvalidDeleteRequestException.java
- src/main/java/com/service/core/letter/application/LetterService.java
- src/main/java/com/service/core/letter/infrastructure/LetterInvoiceRepository.java
- src/main/java/com/service/core/letter/presentation/LetterController.java
자신이 보낸 편지를 삭제할 수 있게 한다.
- resolved #59 
본인이 작성한 편지만 삭제 가능하도록 User Id, Letter Id를 대조하였다.
###
1. 현재 Letter 목록
###
2. [현재 로그인한 사용자 id / 편지를 작성한 사용자 id], [삭제하려는 편지 id / 사용자가 작성한 편지 id] 불일치 시 오류 처리
###
3. 정보 일치 시 성공
4번 편지가 삭제된 것을 확인할 수 있다.
LetterInvoice에서도 삭제를 진행해야 할지 의견 부탁드립니다.
> ✨[Feature/delete-59] 편지 삭제 기능 구현

- .github/workflows/action.yml
- .github/workflows/actionCD.yml
- .github/workflows/actionCI.yml
- appspec.yml
- src/test/java/com/service/core/GlassBottleServiceApplicationTests.java
- src/test/java/com/service/core/letter/application/SendLetterServiceTest.java
- CI/CD 자동화를 위한 설정 구현/추가
- git action 정보 추가
- S3 버킷 생성 및 IAM 사용자 추가
- git action에 S3 내용 추가
- 해당 코드 진행 방식이 맞는지
- 추가해야할 내용이 있는지
-
> [Feature/Git-Action-2] action.yml 내용 추가

- appspec.yml
- scripts/deploy.sh
- CodeDeploy 실행 코드 추가
- resolved #74 
- CodeDeploy 실행 코드 추가
- 해당 구현 방법이 맞는 방법인지
-
> [Feature/git-action-2] CodeDeploy 실행 코드 추가

- .github/workflows/actionCD.yml
- codedeploy 문제 발생
- codedeploy 배포 config 수정
-
> [Fix/git-action] codedeploy 배포 config 수정

- .github/workflows/actionCD.yml
- appspec.yml
- ci/cd 자동화 중 codedeploy-agent 로그에서 Aws::CodeDeployCommand::Client 200 0.024616 0 retries] put_host_command_complete(command_status:"Failed",diagnostics:{format:"JSON",payload:"{\"error_code\":5,\"script_name\":\"\",\"message\":\"bucket name must not contain a forward-slash (/)\",\"log\": 확인
- --s3-location bucket 값을 bucket 명으로 변경
- 
-
> [Fix/Code Deploy] codedeploy 배포 bucket명 변경

- appspec.yml
> deploy 배포 관리 yml 파일 수정

- .github/workflows/actionCD.yml
- .github/workflows/actionCI.yml
- appspec.yml
- 현재 codedeploy DownloadBundle Event [UnknownError] 발생
- code deploy yml 설정 파일 변경
- 추가방안, 잘못된 코드 확인
-
> [Fix/Code Deploy] deploy 배포 관리 yml 파일 수정

- scripts/deploy.sh
- code deploy 작동시 서버에 빌드 되는것을 확인하였으나 서버 실행이 되지 않았음
- resolved #91 
- deploy.sh 파일 명령어 추가 및 경로 수정
- 해당 코드작성 방법이 맞는지
-
> [Fix/Code depoloy] code deploy 실행 파일 명령어 변경

- build.gradle
- src/main/java/com/service/core/common/domain/BaseEntity.java
- src/main/java/com/service/core/letter/application/LetterService.java
- src/main/java/com/service/core/letter/application/RandomSend.java
- src/main/java/com/service/core/letter/convert/LetterConvert.java
- src/main/java/com/service/core/letter/presentation/LetterController.java
- src/main/java/com/service/core/member/domain/User.java
- src/main/java/com/service/core/member/infrastructure/MemberRepository.java
- src/test/java/com/service/core/letter/application/SendLetterServiceTest.java
전체 유저 중, MBTI에 상관없이 랜덤으로 10명에게 편지를 발송할 수 있게 한다.
- resolved #78 
전체 유저 중 10명에게 랜덤으로 편지 전송 시 다음과 같이 DB에 저장된다.
받는 사람의 MBTI ID는 0으로 설정하였다. (0 == All User)
Redis Cache는 아직 적용이 안 되었습니다.
추후 개선할 예정입니다.
> ✨[Feature/random-78] 전체 랜덤 대상 설정 구현

- build.gradle
- src/main/java/com/service/core/common/domain/BaseEntity.java
- src/main/java/com/service/core/letter/application/LetterSchedulerService.java
- src/main/java/com/service/core/letter/application/LetterService.java
- src/main/java/com/service/core/letter/application/RandomSend.java
- src/main/java/com/service/core/letter/convert/LetterConvert.java
- src/main/java/com/service/core/letter/infrastructure/LetterRepository.java
- src/main/java/com/service/core/letter/presentation/LetterController.java
- src/main/java/com/service/core/member/domain/User.java
- src/main/java/com/service/core/member/infrastructure/MemberRepository.java
- src/test/java/com/service/core/letter/application/LetterSchedulerServiceTest.java
- src/test/java/com/service/core/letter/application/SendLetterServiceTest.java
30일이 지난 편지를 자동으로 삭제한다.
- resolved #79 
생성일로부터 30일이 지난 편지를 매일 자정마다 삭제한다.
LetterInvoice도 연동하여 같이 삭제해야 할까요?
그리고 스케줄링 테스트 코드는 어떻게 짜야 하는지 아시는 분 있으면 알려주세요...
> ✨[Feature/delete-79] 편지 자동 삭제 기능을 구현한다.

- build.gradle
- src/main/java/com/service/core/common/domain/BaseEntity.java
- src/main/java/com/service/core/letter/application/LetterSchedulerService.java
- src/main/java/com/service/core/letter/application/LetterService.java
- src/main/java/com/service/core/letter/application/RandomSend.java
- src/main/java/com/service/core/letter/convert/LetterConvert.java
- src/main/java/com/service/core/letter/infrastructure/LetterInvoiceRepository.java
- src/main/java/com/service/core/letter/infrastructure/LetterRepository.java
- src/main/java/com/service/core/letter/presentation/LetterController.java
- src/main/java/com/service/core/member/domain/User.java
- src/main/java/com/service/core/member/infrastructure/MemberRepository.java
- src/test/java/com/service/core/letter/application/LetterSchedulerServiceTest.java
- src/test/java/com/service/core/letter/application/SendLetterServiceTest.java
사용자가 직접 편지를 삭제하는 것이 아닌, 스케줄러를 통해 30일마다 자동으로 삭제되도록 방안을 바꾸었다.
- resolved #90 
기존에 만들었던 편지 단건 삭제 기능을 제거하였다.
> 🔥[Feature/delete-90] 편지 단건 삭제 기능 제거

- .github/workflows/actionCICD.yml
- appspec.yml
- scripts/deploy.sh
- codedeploy 설정 디렉토리 변경
- codedeploy 설정 디렉토리 변경
-
-
> [Fix/cicd] codedeploy 설정 디렉토리 변경

- scripts/deploy.sh
- 서버 내의 프로세스 종료 후 재시작이 되지 않음
- 서버 내의 프로세스 종료 후 재시작이 안되어 명령어 수정
-
-
> [Fix/cicd] deploy 명령어 수정

- .github/workflows/actionCICD.yml
- scripts/deploy.sh
- 현재 배포 파일을 ec2에 받았으나 deploy.sh 를 통해 해당 jar파일 실행되고 있지 않음
- 우선 staging 브런치 pr로도 git-action 작동으로 설정
- 현재 jar 실행하려는 위치 로그 확인
- 
-
> [Fix/CI-CD] 배포 파일 실행

- src/main/java/com/service/core/error/dto/ErrorMessage.java
- src/main/java/com/service/core/error/exception/member/PasswordMismatchException.java
- src/main/java/com/service/core/member/convert/MemberConvert.java
- src/main/java/com/service/core/member/domain/vo/Email.java
- src/main/java/com/service/core/member/domain/vo/Password.java
- resolved #38 
- 이메일 생성시 이메일 형식이 아닐경우 예외처리
- 비밀번호 최소 4자리 이상 입력 예외처리
> :recycle:[Feature/login] 회원 생성기능 예외처리 추가

- build.gradle
테스트 커버리지를 측정하기 위해 Jacoco를 도입한다.
- resolved #103 
프로젝트 실행 시 다음과 같이 html 파일에서 테스트 커버리지 측정 결과를 확인할 수 있다.
> ✨[Feature/jacoco-103] Jacoco 기능 추가

- build.gradle
테스트 코드를 더 간편하게 작성하기 위해 Fixture Monkey를 도입한다.
- resolved #105 
build.gradle에 Fixture Monkey 라이브러리 추가
> ✨[Feature/jacoco-105] Fixture Monkey 기능 추가

- build.gradle
- src/main/java/com/service/core/error/dto/ErrorMessage.java
- src/main/java/com/service/core/error/exception/letter/QRConversionFailedException.java
- src/main/java/com/service/core/letter/application/LetterService.java
- src/main/java/com/service/core/letter/dto/response/SharingResponse.java
- src/main/java/com/service/core/letter/presentation/LetterController.java
- 보낸 편지와 받은 편지 값을 담은 편지 공유 기능 구현
- 보낸 편지와 받은 편지 값을 담은 편지 공유 기능 구현
- 로그인 상태의 아이디가 보낸편지의 아이디와 맞는지 유효성 검사
- 보낸편지와 받은 편지의 객체정보를 ShraingResponse 객체로 생성
- 해당 객체를 JsonString값 데이터로 QR 생성 후 해당 데이터도 String으로 변환 및 반환
- 현재 작동확인하지 못하였음. 이후 편지 전달/발송 폼을 팀원에게 받아 테스트 예정
- 이후 qr데이터도 String으로 받기 때문에 QR코드 생성 확인은 어려울 수 있음
-
> [Feature/Sharing] 편지 공유 기능 구현

- .github/workflows/actionCICD.yml
- 기능 구현 마무리
- PR시 git action 실행 취소
- PR시 git action 실행 취소
-
-
> [Fix/git-action] PR시 git action 실행 취소

- .github/workflows/actionCICD.yml
- appspec.yml
- src/main/java/com/service/core/auth/application/AuthUserService.java
- src/main/java/com/service/core/letter/application/LetterSchedulerService.java
- src/main/java/com/service/core/letter/application/LetterService.java
- src/main/java/com/service/core/letter/application/RandomSend.java
- src/main/java/com/service/core/mbti/application/MbtiMetadataService.java
- ec2 connection pool error 발생
- org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
- HikariPool-1 - Thread starvation or clock leap detecte
- Service Transaction annotation 추가  
- 특이사항 있는지, 잘못 추가하였는지
> [Fix/Service-Transaction] Service Transaction annotation 추가  

- .github/workflows/actionCICD.yml
- scripts/deploy.sh
- src/main/java/com/service/core/letter/application/LetterSchedulerService.java
- src/main/java/com/service/core/letter/application/LetterService.java
- src/main/java/com/service/core/letter/application/RandomSend.java
- src/main/java/com/service/core/member/application/MemberService.java
- src/main/resources/logback-slack.xml
- 현재 connection pool error로 서버 다운
- 중첩 트랜잭션 조금 제거
- application.yml data.redis 설정 변경
- 코드 에러 사항
> [Fix/transaction] Transaction 중복 제거 및 redis 설정 변경

- src/test/java/com/service/core/auth/application/AuthUserServiceTest.java
- src/test/java/com/service/core/member/application/MemberServiceTest.java
> [Feature/login] :white_check_mark: Add or update tests

- src/main/java/com/service/core/letter/application/LetterService.java
- src/test/java/com/service/core/letter/application/SharingLetterTest.java
- 편지 공유 기능 단위 테스트 진행
- zxing 라이브러리를 통해 값이 잘 변환되는지 확인
-
-
> [Feature/Letter-Sharing] 공유 기능 단위 테스트

- .github/workflows/actionCICD.yml
- README.md
@HwangHarim 
@sonrose 
@InJun2 
- resolved #0
> 📝[Docs]: 회고록 추가
